const nodemailer = require('nodemailer');
const env = require('../config/env');
const winston = require('winston');

const logger = winston.createLogger({
  level: 'info',
  format: winston.format.combine(winston.format.timestamp(), winston.format.json()),
  transports: [new winston.transports.Console()],
});

// Configure transporter
let transporter = null;

try {
  transporter = nodemailer.createTransport({
    host: env.SMTP_HOST || 'smtp.gmail.com',
    port: parseInt(env.SMTP_PORT, 10) || 587,
    secure: false, // true for 465, false for other ports
    auth: {
      user: env.SMTP_USER,
      pass: env.SMTP_PASS,
    },
  });
  logger.info('SMTP Mail Service successfully initialized');
} catch (err) {
  logger.error('Failed to initialize SMTP Mail Service:', err.message);
}

/**
 * Send an onboarding credential email to a newly created User or Admin.
 * @param {string} toEmail - Recipient email.
 * @param {string} toName - Recipient full name.
 * @param {string} role - User role ('admin', 'agent').
 * @param {string} password - Raw temporary password.
 * @param {string} orgName - Associated organization name.
 * @returns {Promise<boolean>} - True if sent successfully.
 */
async function sendOnboardingEmail(toEmail, toName, role, password, orgName = 'WhatsApp Platform') {
  if (!transporter || !env.SMTP_USER || !env.SMTP_PASS) {
    logger.warn('SMTP credentials not configured. Skipping onboarding email.');
    return false;
  }

  const roleLabel = role === 'admin' ? 'Organization Administrator' : 'Support Agent / Telecaller';
  const loginUrl = env.FRONTEND_URL || 'http://localhost:3000';

  const mailOptions = {
    from: env.FROM_EMAIL || env.SMTP_USER,
    to: toEmail,
    subject: `Welcome to ${orgName} - Your Onboarding Credentials`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 30px; border: 1px solid #e2e8f0; border-radius: 16px; background-color: #ffffff; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);">
        <div style="text-align: center; margin-bottom: 25px; border-bottom: 2px solid #f1f5f9; padding-bottom: 20px;">
          <h2 style="color: #0f172a; margin: 0; font-size: 24px; font-weight: 700; letter-spacing: -0.5px;">Welcome to ${orgName}!</h2>
          <p style="color: #64748b; margin: 5px 0 0 0; font-size: 14px;">Your Enterprise WhatsApp Marketing Platform</p>
        </div>
        
        <p style="font-size: 16px; color: #334155; line-height: 1.6; margin-top: 0;">
          Hello <strong>${toName}</strong>,
        </p>
        
        <p style="font-size: 15px; color: #475569; line-height: 1.6;">
          An organization account has been successfully created for you as an <strong>${roleLabel}</strong>. You can now log into your dashboard using the credentials below.
        </p>

        <div style="margin: 25px 0; padding: 20px; background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px;">
          <h4 style="margin: 0 0 12px 0; color: #0f172a; font-size: 15px; font-weight: 600; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px;">Your Credentials:</h4>
          <table style="width: 100%; font-size: 14px; border-collapse: collapse;">
            <tr>
              <td style="padding: 6px 0; color: #64748b; width: 120px;"><strong>Username/Email:</strong></td>
              <td style="padding: 6px 0; color: #0f172a; font-family: monospace;"><strong>${toEmail}</strong></td>
            </tr>
            <tr>
              <td style="padding: 6px 0; color: #64748b;"><strong>Password:</strong></td>
              <td style="padding: 6px 0; color: #0f172a; font-family: monospace;"><strong>${password}</strong></td>
            </tr>
            <tr>
              <td style="padding: 6px 0; color: #64748b;"><strong>Role Context:</strong></td>
              <td style="padding: 6px 0; color: #3b82f6; font-weight: 600;">${roleLabel}</td>
            </tr>
          </table>
        </div>

        <div style="text-align: center; margin: 30px 0 20px 0;">
          <a href="${loginUrl}/login" target="_blank" style="background-color: #2563eb; color: #ffffff; padding: 14px 28px; text-decoration: none; border-radius: 8px; font-weight: 600; font-size: 15px; display: inline-block; box-shadow: 0 4px 6px -1px rgba(37, 99, 235, 0.2);">
            Log In to Dashboard
          </a>
        </div>

        <p style="font-size: 13px; color: #94a3b8; line-height: 1.5; border-top: 1px solid #f1f5f9; padding-top: 20px; margin-bottom: 0;">
          <strong>Security Note:</strong> This is a temporary password generated by your administrator. For your security, you will be prompted to set a new, secure password upon your first login.
        </p>
      </div>
    `,
  };

  try {
    logger.info(`Sending onboarding email to ${toEmail}...`);
    const info = await transporter.sendMail(mailOptions);
    logger.info(`Onboarding email successfully delivered. Message ID: ${info.messageId}`);
    return true;
  } catch (error) {
    logger.error('Failed to deliver onboarding email:', error);
    return false;
  }
}

module.exports = {
  sendOnboardingEmail,
};
