/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        brand: { 50: '#ecfdf5', 100: '#d1fae5', 200: '#a7f3d0', 300: '#6ee7b7', 400: '#34d399', 500: '#10b981', 600: '#059669', 700: '#047857', 800: '#065f46', 900: '#064e3b' },
        dark: { 50: '#f8fafc', 100: '#f1f5f9', 200: '#e2e8f0', 300: '#cbd5e1', 400: '#94a3b8', 500: '#64748b', 600: '#475569', 700: '#334155', 800: '#1e293b', 900: '#0f172a', 950: '#020617' },
        // WhatsApp Web exact color palette
        wa: {
          green: '#00a884',
          'green-dark': '#006b53',
          'green-light': '#25d366',
          teal: '#005c4b',
          'teal-deep': '#00a884',
          // Light mode
          'bg': 'var(--bg-primary)',
          'panel': 'var(--bg-card)',
          'panel-header': 'var(--wa-panel-header)',
          'header': '#e5eff8',
          'chat-bg': 'var(--wa-chat-bg)',
          'bubble-out': 'var(--wa-bubble-out)',
          'bubble-in': 'var(--wa-bubble-in)',
          'input-bg': 'var(--wa-input)',
          'hover': 'var(--wa-hover)',
          'border': 'var(--wa-border)',
          'search': 'var(--wa-search)',
          // Dark mode
          'dark-bg': 'var(--bg-primary)',
          'dark-panel': 'var(--bg-card)',
          'dark-panel-header': 'var(--wa-panel-header)',
          'dark-header': '#202c33',
          'dark-chat-bg': 'var(--wa-chat-bg)',
          'dark-bubble-out': 'var(--wa-bubble-out)',
          'dark-bubble-in': 'var(--wa-bubble-in)',
          'dark-input': 'var(--wa-input)',
          'dark-hover': 'var(--wa-hover)',
          'dark-border': 'var(--wa-border)',
          'dark-search': 'var(--wa-search)',
          // Text
          'text-primary': 'var(--text-primary)',
          'text-secondary': 'var(--text-secondary)',
          'text-light': '#8696a0',
          'dark-text-primary': 'var(--text-primary)',
          'dark-text-secondary': 'var(--text-secondary)',
        },
        // Theme variables mapping
        themeBg: 'var(--background)',
        themeSurface: 'var(--surface)',
        themeCard: 'var(--card)',
        themeCardHover: 'var(--card-hover)',
        themeBorder: 'var(--border)',
        themeTextPrimary: 'var(--text-primary)',
        themeTextSecondary: 'var(--text-secondary)',
        themeMuted: 'var(--muted)',
        themeInputBg: 'var(--input-bg)',
        themeInputBorder: 'var(--input-border)',
        themeInputText: 'var(--input-text)',
        themePlaceholder: 'var(--placeholder)',
        themeTableHeader: 'var(--table-header)',
        themeTableRow: 'var(--table-row)',
        themeTableRowAlt: 'var(--table-row-alt)',
        themeTableRowHover: 'var(--table-row-hover)',
      },
      fontFamily: { sans: ['Inter', 'system-ui', 'sans-serif'] },
      boxShadow: {
        'wa': '0 1px 3px rgba(11,20,26,0.08)',
        'wa-md': '0 2px 8px rgba(11,20,26,0.12)',
        'wa-lg': '0 4px 16px rgba(11,20,26,0.16)',
      },
    },
  },
  plugins: [],
};
